repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
      - id: go-critic
      - id: go-mod-tidy