version: "3"
services:
  twitch-views-postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: twitch-views-service-postgres
    volumes:
      - twitch-views-service-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  # twitch-views-service-app:
  #   image: twitch-views-service:latest
  #   network_mode: bridge
  #   container_name: twitch-views-service-app
  #   build: .
  #   expose:
  #     - 8880
  #   ports:
  #     - 8880:8880
  #   depends_on:
  #     - twitch-views-service-postgres
  #   links:
  #     - twitch-views-service-postgres
volumes:
  twitch-views-service-data: